Let us illustrate how to use our code. <br>
As the first thing, we import the libraries and the definitions needed.

In [1]:
import numpy as np
from numpy.polynomial import polynomial as P
from itertools import product
import matplotlib.pyplot as plt
import time
from Definitions import *

Then, we introduce our functions with an example based on a simple CY three-fold. <br>
Let us start with the exact formula...

In [2]:
# Define the weight system
example_weight_threefold = [10, 27, 53, 85, 175]

# Finds both the exact result and the approximation, and saves the time needed to compute the full formula.
start_time = time.time()
exact_poly, approx_poly = Poincare_clean(np.array(np.array(example_weight_threefold)))
end_time = time.time()
compute_time_exact = end_time - start_time

print(f"The full polynomial is:\n{exact_poly}")
print(f"...from which we read the following non-trivial Hodge numbers: [h11, h12] = {Hodge_reader_3folds(exact_poly)}")
print(f"\nThe computational time was: {compute_time_exact} seconds")


The full polynomial is:
[[  1.   3.   3.]
 [ 14.   2.   2.]
 [ 14.   1.   1.]
 [  1.   0.   0.]
 [ -1.   0.   3.]
 [-84.   1.   2.]
 [-84.   2.   1.]
 [ -1.   3.   0.]]
...from which we read the following non-trivial Hodge numbers: [h11, h12] = [14.0, 84.0]

The computational time was: 2.4844539165496826 seconds


And we now move to the approximation on its own...

In [3]:
# Finds the approxiamted Hodge numbers using truncated formula, and saves the time needed to calculate.
start_time = time.time()
approximated_poly = Poincare_approx_clean(np.array(np.array(example_weight_threefold)))
end_time = time.time()
compute_time_approx = end_time - start_time

print(f"The truncated polynomial is:\n{approximated_poly}")
print(f"...from which we read the following approximated Hodge numbers: {Hodge_reader_3folds(approximated_poly)}")
print(f"\nThe computational time was: {compute_time_approx} seconds")


The truncated polynomial is:
[[  1.   3.   3.]
 [ 10.   2.   2.]
 [ 10.   1.   1.]
 [  1.   0.   0.]
 [ -1.   0.   3.]
 [-84.   1.   2.]
 [-84.   2.   1.]
 [ -1.   3.   0.]]
...from which we read the following approximated Hodge numbers: [10.0, 84.0]

The computational time was: 0.11216497421264648 seconds


Extending these results to the consideration of a CY four-fold...

In [4]:
# Define the weight system
example_weight_fourfold = [ 10,  27,  36,  38, 159, 234]

# Finds both the exact result and the approximation, and saves the time needed to compute the full formula.
start_time = time.time()
exact_poly, approx_poly = Poincare_clean(np.array(np.array(example_weight_fourfold)))
end_time = time.time()
compute_time_exact = end_time - start_time

# Finds the approxiamted Hodge numbers using truncated formula, and saves the time needed to calculate.
start_time = time.time()
approximated_poly = Poincare_approx_clean(np.array(np.array(example_weight_fourfold)))
end_time = time.time()
compute_time_approx = end_time - start_time

print(f"The full polynomial is:\n{exact_poly}")
print(f"...from which we read the following Hodge numbers: [h11, h12, h13, h22] = {Hodge_reader_4folds(exact_poly)}")
print(f"The computational time was: {compute_time_exact} seconds")
print("---------------------------------------")
print(f"The truncated polynomial is:\n{approximated_poly}")
print(f"...from which we read the following approximated Hodge numbers:[h11, h12, h13, h22] = {Hodge_reader_4folds(approximated_poly)}")
print(f"The computational time was: {compute_time_approx} seconds")


The full polynomial is:
[[  1.   4.   4.]
 [122.   3.   3.]
 [824.   2.   2.]
 [122.   1.   1.]
 [  1.   0.   0.]
 [  1.   0.   4.]
 [ 76.   1.   3.]
 [ 76.   3.   1.]
 [ -6.   2.   3.]
 [ -6.   1.   2.]
 [ -6.   3.   2.]
 [ -6.   2.   1.]
 [  1.   4.   0.]]
...from which we read the following Hodge numbers: [h11, h12, h13, h22] = [122.0, 6.0, 76.0, 824.0]
The computational time was: 6.788607120513916 seconds
---------------------------------------
The truncated polynomial is:
[[  1.   4.   4.]
 [118.   3.   3.]
 [787.   2.   2.]
 [118.   1.   1.]
 [  1.   0.   0.]
 [  1.   0.   4.]
 [ 75.   1.   3.]
 [ 75.   3.   1.]
 [  1.   4.   0.]]
...from which we read the following approximated Hodge numbers:[h11, h12, h13, h22] = [118.0, 0, 75.0, 787.0]
The computational time was: 0.14397406578063965 seconds


We now demonstrate the computation of the Euler number (exactly) for the example weight system...

In [5]:
# Define the weight system
example_weight_fourfold = [ 10,  27,  36,  38, 159, 234]

#Compute the Euler number of Calabi-Yau hypersurface of the weight system's respective weighted projective space.
euler = EulerNumber(example_weight_fourfold)

print(f"The euler number is:\n{euler}")


The euler number is:
-1200


Alternatively one can check an input weight system for the intradivisibility property...

In [6]:
# Define the weight system
example_weight_fourfold = [ 10,  27,  36,  38, 159, 234]

#Compute the intravisibility check (as a boolean True/False output)
D = intradivisibility(example_weight_fourfold)

print(f"Is this weight system intradivisible? --> {D}")


Is this weight system intradivisible? --> True
