In [6]:
print("Let us illustrate how to use our code")
print("As the first thing, we import the libraries and the definitions needed")

Let us illustrate how to use our code
As the first thing, we import the libraries and the definitions needed


In [7]:
import numpy as np
from numpy.polynomial import polynomial as P
from itertools import product
import matplotlib.pyplot as plt
import time
from Definitions import *

In [8]:
print("Then, we introduce our functions with an example based on a simple C-Y three-fold")
print("Let us start with the exact formula")

Then, we introduce our functions with an example based on a simple C-Y three-fold


In [13]:
example_weight_threefold = [10, 27, 53, 85, 175]
# Define the weight system

start_e = time.time()
exact_poly, approx_poly = Poincare_clean(np.array(np.array(example_weight_threefold)))
end_e = time.time()
time_e = end_e - start_e
# Finds both the exact result and the approximation, and saves the time needed to compute the full formula.

print("The full polynomial is:")
print(exact_poly)
print("...from which we read the following non-trivial Hodge numbers: [h11, h12] = ", Hodge_reader_3folds(exact_poly))
print("The computational time was:")
print(time_e, "seconds")

The full polynomial is:
[[  1.   3.   3.]
 [ 14.   2.   2.]
 [ 14.   1.   1.]
 [  1.   0.   0.]
 [ -1.   0.   3.]
 [-84.   1.   2.]
 [-84.   2.   1.]
 [ -1.   3.   0.]]
...from which we read the following non-trivial Hodge numbers: [h11, h12] =  [14.0, 84.0]
The computational time was:
11.964545249938965 seconds


In [14]:
print("And we now move to the approximation")

And we now move to the approximation


In [15]:
start_a = time.time()
approximated_poly = Poincare_approx_clean(np.array(np.array(example_weight_threefold)))
end_a = time.time()
time_a = end_a - start_a
# Finds the truncated version, and saves the time needed to calculate it.

print("The truncated polynomial is:")
print(approximated_poly)
print("...from which we read the following approximated Hodge numbers: ", Hodge_reader_3folds(approximated_poly))
print("The computational time was:")
print(time_a, "seconds")

The truncated polynomial is:
[[  1.   3.   3.]
 [ 10.   2.   2.]
 [ 10.   1.   1.]
 [  1.   0.   0.]
 [ -1.   0.   3.]
 [-84.   1.   2.]
 [-84.   2.   1.]
 [ -1.   3.   0.]]
...from which we read the following approximated Hodge numbers:  [10.0, 84.0]
The computational time was:
0.330125093460083 seconds


In [ ]:
print("And now a C-Y four-fold")

In [17]:
example_weight_fourfold = [ 10,  27,  36,  38, 159, 234]

start_e = time.time()
exact_poly, approx_poly = Poincare_clean(np.array(np.array(example_weight_fourfold)))
end_e = time.time()
time_e = end_e - start_e
# Finds both the exact result and the approximation, and saves the time needed to compute the full formula.

start_a = time.time()
approximated_poly = Poincare_approx_clean(np.array(np.array(example_weight_fourfold)))
end_a = time.time()
time_a = end_a - start_a
# Finds the truncated version, and saves the time needed to calculate it.

print("The full polynomial is:")
print(exact_poly)
print("...from which we read the following Hodge numbers: [h11, h12, h13, h22] = ", Hodge_reader_4folds(exact_poly))
print("The computational time was:")
print(time_e, "seconds")
print("---------------------------------------")
print("The truncated polynomial is:")
print(approximated_poly)
print("...from which we read the following approximated Hodge numbers:[h11, h12, h13, h22] = ", Hodge_reader_4folds(approximated_poly))
print("The computational time was:")
print(time_a, "seconds")

The full polynomial is:
[[  1.   4.   4.]
 [122.   3.   3.]
 [824.   2.   2.]
 [122.   1.   1.]
 [  1.   0.   0.]
 [  1.   0.   4.]
 [ 76.   1.   3.]
 [ 76.   3.   1.]
 [ -6.   2.   3.]
 [ -6.   1.   2.]
 [ -6.   3.   2.]
 [ -6.   2.   1.]
 [  1.   4.   0.]]
...from which we read the following Hodge numbers: [h11, h12, h13, h22]=  [122.0, 6.0, 76.0, 824.0]
The computational time was:
33.12689161300659 seconds
---------------------------------------
The truncated polynomial is:
[[  1.   4.   4.]
 [118.   3.   3.]
 [787.   2.   2.]
 [118.   1.   1.]
 [  1.   0.   0.]
 [  1.   0.   4.]
 [ 75.   1.   3.]
 [ 75.   3.   1.]
 [  1.   4.   0.]]
...from which we read the following approximated Hodge numbers:[h11, h12, h13, h22]=  [118.0, 0, 75.0, 787.0]
The computational time was:
0.6770708560943604 seconds
